export default [
  { id: "1", imageName: "destination-img01.jpg", tag: "popular", place: "Sigiriya" },
  { id: "2", imageName: "destination-img02.jpg", tag: "popular", place: "Nine Arch Bridge" },
  { id: "3", imageName: "destination-img03.jpg", tag: "romantic", place: "Arugambay Beach" },
  { id: "4", imageName: "destination-img04.jpg", tag: "romantic", place: "Mini Adam's Peak" },
  { id: "5", imageName: "destination-img05.jpg", tag: "popular", place: "Ambuluwawa Tower" },
  { id: "6", imageName: "destination-img06.jpg", tag: "popular", place: "Ravana Waterfall" },
  { id: "7", imageName: "destination-img07.jpg", tag: "romantic", place: "Upper Diyaluma" },
  { id: "8", imageName: "destination-img08.jpg", tag: "popular", place: "Temple of Tooth Relic" },
  { id: "10", imageName: "destination-img10.jpg", tag: "new", place: "Boburu Ella" },
  { id: "11", imageName: "destination-img11.jpg", tag: "new", place: "Pidurangala" },
  { id: "12", imageName: "destination-img12.jpg", tag: "popular", place: "Horton Plains"},
  { id: "13", imageName: "destination-img13.jpg", tag: "romantic", place: "Coconut Tree Hill" },
  { id: "14", imageName: "destination-img14.jpg", tag: "popular", place: "Galle Fort" },
];
